[[constraint]]
name = "github.com/buildkite/terminal-to-html"
version = "3.2.0"

[[constraint]]
name = "github.com/gliderlabs/ssh"
version = "0.1.3"

[[constraint]]
name = "github.com/urfave/cli"
version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
